### ISSUE TITLE
27 seconds limit

### ISSUE THREAD

**Issue by goretoxo** [undessens/Lucibox#1]
I've built a pedal loop following your instructions, and after having it ready for using, now I find there is some recording limit of about 27 seconds in any loop. Any help with this? Is threre any kind on forced limit in the loops recording time?

thanks.

**Comment by undessens** [comment]
Hello

First . Congratulation if you built it . I really would like to have photos
of it and publish it.
Then about the limitation : yes you can change it .  Do you know a bit
about puredara or not ? If yes it's really simple , if not, i have to
explain to you with some screenshot .

Regards

**Comment by goretoxo** [comment]
oh, great!!
So far my looper looks like this:
https://ecohorta.org/2019/05/26/moon_loopstation/

This is my first puredata project, but before using your patches, I've done some investigation on other loop patches in puredata tutorials. If it's as simple as changing some value in the .pd files, tell me. If it's harder, I'll try my best.

Thanks for your work, and for your attention.

**Comment by goretoxo** [comment]
looking in the pd patches, I've found some 1.2e+06 references. 
If 1.2e+06 / 44100 = 27.2, maybe those references are the limits I'm looking for?

The places are:
 patches/audio/recloopsave.pd
 patches/audio/readloop.pd
 patches/audio/recloopsavesampler.pd

**Comment by undessens** [comment]
Yes exactly . 

Your pedal looks really good. I really would like to realise a gallery of all people who built it. It would be great.
Can you send me more picture, and a name or pseudo you want to associate with it ?


You were right about the 1,2e+06 : this is the point . This is the size of the “table” which is containing the sound of the loop.
 But be careful, you need to change 2 times.
The first one is in subpath “pd init” , located in the top left corner of the looper patch. Double click to enter , or right click “open"
The second one, a the bottom right of the patch.

I saw that you add potentiometers right ? Do you know how to connect them to the software ? There is a “learnt” module for each parameter.

Hope to see you soon.

Aurélien

**Comment by goretoxo** [comment]
I can send you more photos via email. It would be nice to publish  photos and testimonials of all the "makers" of the moon loopstation, from your workshops as well as those like me at their own risk. It could be the birthplace of a community...

I've done the suggested change, and now I can record up to 4,5minutes per voice. Fine.

Yes: I've added four more potentiometers (by now not connected to anything) thinking on controlling the volume of each voice, probably. I haven't tried to connect (neither software nor hardware) them yet.

Now some other "problems":

- the "song selection" potentiometer is supposed to select one "song" by lighting in white one of the 12 leds, and then, as you turn it, the different lights go on and off (as seen in your demo video). But mine doesn't: When you turn the knob, the leds just go out. 

-  Sometimes the signals of the potentiometers get crossed, or something like that: the first one (for the mic sendA signal) moves the mic sendA signal, AND the SONG SELECTION... 

- it would be nice to have some button for ordered shutdown. Now we must logon the raspi via ethernet (or wifi) and from there shutdown the system.

thanks

**Comment by undessens** [comment]
Whow this is really strange …

About the song selection. Leds are supposed to be “blue”. On the User interface, you got something “song” at the bottom right corner. Here, you got a number and “+” and “-“ button. If you click on it, the leds are supposed to move up and down, exactly as if you turn the potentiometers. 

Then in the CONNECT section, be sure of the value of potentiometer that comes from the Arduino. There is a some rectangle with Arduino IN. Here all the value coming form the Arduino appears. 

And about the crossed value … this is super strange. I think this is more hardware, like ground not connected to the potentiometers or 5v not connected to potentiometers… or eventually Arduino analog input broken . 

Yes please, send me the picture btw

**Comment by goretoxo** [comment]
blue, white... "not red, not green"...
;-)

I've disconnected all the analog inputs from the arduino, and tried with the "+" and "-" buttons in the puredata interface. The "song" changes in the puredata display, but the leds don't change.

More on: after recording one track, I've "blue" and "green" leds on. If i click on the "+" or  "-" buttons in the puredata interface, but the leds are still "blue" and "green".

Just for testing: how could I connect other slider functions in your patch with arbitrary analog inputs of the arduino? The arduino has up to 7 analog inputs, so I could link them to 7 different functions. I suppose I must increase the analog reading array in the arduino sketch, but the puredata side is what I don't know.

thanks, again, for your time.

**Comment by goretoxo** [comment]
I don't have your email to send you images of my pedal. Could you please send it?

**Comment by goretoxo** [comment]
solved all the issues!
a) the potentiometers working, and changing each voice volume:
on the arduino sketch changed line 19:
#define ANALOGIN 7
and line 31:
int analogPin[] = { A0, A1, A2, A3, A4, A5, A6, A7};
on the patch, just added the needed values in the presets files:
preset/midiLearn_1_1_looper_volume.txt:
3 3 0
preset/midiLearn_2_1_looper_volume.txt:
3 4 0
... and so on

b) the song selection leds on and off:
on the arduino sketch, after seeing that other invocations of the setOneNeoPixel function had multipliers on the values, just changed line 140 of the sketch to:
setOneNeoPixel( value, 0, 25*255, 25*255);

and now the channel lights work!!

**Comment by undessens** [comment]
Impressive ... good job . Going deep into it is a huge challenge. Can't
wait to see your pictures

**Comment by ghost** [comment]
> looking in the pd patches, I've found some 1.2e+06 references.
> If 1.2e+06 / 44100 = 27.2, maybe those references are the limits I'm looking for?
> 
> The places are:
> patches/audio/recloopsave.pd
> patches/audio/readloop.pd
> patches/audio/recloopsavesampler.pd

Can you please your edited (3) files? I can't find 1.2e+06 on readloop.pd
Thanks

**Comment by goretoxo** [comment]
back to lucibox, one yeaar later. Nice to see that there are more looper builders!
Now, at last, I've used the v2 img from patchbox, and mostly everything works fine out of the box!
Still need some time to test the new machines (specially number 8...), but my updated looper with number #1 works fine as well..

just one "little problem": I've searched again for "1.2e+06" in the patches subdir, and found now there are 21 occurrences of the string.... I'll change them but could we have some place in the puredata sketches where this value is defined as a variable?

**Comment by AurelienConil** [comment]
Hi goretoxo . Thanks you for the nice words, i am still improving the homemade loop factory. My goal actually is to create an sd card with fat32 partition beside the linux partition, that will make easier the transfer of file between computer and rpi machine. I have now some time to work on it.
Unfortunatly there is no "config.h" file that enable to set global variables actually, but the search command is pretty change, and recognize all the instance as a new "search found".  There is only one file to edit, which loop.pd ( if you are using the last version ), and change it inside "pd init".
