### ISSUE TITLE
Connect new buttons to Arduino and broken version

### ISSUE THREAD

**Issue by ghost** [undessens/Lucibox#6]
First of all thank you for this loop machine!
I add a mute button for each track http://monkey-lab.net/Lucibox/machines/1/ (once.pd , my_mod_mute.pd and moon_loopstation.pd
and I would like to connect it to Arduino. Can you help me with it?

p.s. the last version of Machine 1 on Github is broken, so I use the 4 Dec 2019 version.

Thanks

**Comment by undessens** [comment]
Hi.
I am changing the .git in several ways these days, particularly adding a "undo" button, web page control. I didn't used a "dev" branch and that is why the actual master branch is broken.

In order to add state controled with the arduino, you need to go to the "Connect" section.
In it there is serveral patches call "connect_smth". In it, there is a patch call "extra/midiLearn".

Use it creating an object called "extra/midiLearn nameOfcontrol" , where 'nameOfControl' is an unique id and also the file name associated in the "preset folder". Trough this object, you can control puredata with an arduino in, midi input or keyboard input. Click on the red toogle to activate learning, a window appear,  then press the arduino or midi input to save the input.

At this time, midiLearn is working but is linked to nothing. I used "extra/sv" patch for connecting an unique parameter trough different location. You can use it in the same way than "extra/sv $1_$2_looper_volume" that control the volume.

Hope this is gonna help

**Comment by ghost** [comment]
Hi,
thanks for your reply.
I went to moon_loopstation > connect > but I don't see connect_smth ... do you do I have to create a new one?

**Comment by undessens** [comment]
No actually, there is 2 two kind of patches, the "ui" one and the "basic" one , let's say.
So , in connect you have big "ui" patches, that you can open, clicking right on it then click on`open` .  The location of these patches are in patches/connect

**Comment by ghost** [comment]
So I have to go to patches>connect> and create connect_mute ??

**Comment by AurelienConil** [comment]
If it is a mute for each loop, it is better to edit `connect > connect_recloopsave ` 
if it is a global mute, you can create extra/midiLearn directly in ` connect `

**Comment by ghost** [comment]
Thank you! 
Anyway, it is better to use mute instead of play/stop for each loop. So you can 'stop' any loop anytime you want.

**Comment by undessens** [comment]
There is a way to activate stop without waiting for the end the bar.
This is what you are looking for ?

**Comment by ghost** [comment]
Yes, I am looking for that function.
Also, looking for function overdub without waiting for the end of the bar, is it there?

**Comment by ghost** [comment]
Overdub without waiting for the end of the bar......If you can make that function this looper will be perfect! I think a lot of people will build this looper :)

**Comment by undessens** [comment]
ok. Overdub is going to be updated in the new version.
For the action on the stop function : 
You have to open the `audio/recloopsaveundo` then find a subpatch call `managePlaying` . Here you can find the "path" of the programme when pressing the play button according to the "state" of the  looper.
In it, `r tempo_quantif_bang` give a bang at the beggining of the bar. 
This can be change for `r tempo_click_bang` to start at the next click not the next bar.
if you remove this `r thing`and connect directly this big green bang to the output, the looper will start directy and will be out of sync.

**Comment by ghost** [comment]
Great news about overdub!!!! when will it be there? 
Out of sync is not a good idea. So mute is the best option.... so you can use mine http://monkey-lab.net/Lucibox/machines/1/

The function stop/play all works perfectly

**Comment by ghost** [comment]
Hi, I try to adjust the 27-sec loop limit. 
I've found the patches/audio/recloopsave.pd, patches/audio/recloopsavesampler.pd
But I can't find 1.2e+06 on patches/audio/readloop.pd ...can you help me?

**Comment by AurelienConil** [comment]
Hi

recloopsavesampler, is the patch that let you record AND play the loop.
Readloop, is an old patch for playing small audio samples, like a drum machine.

If you want to play only with a loop station, you doesn’t have to play with readloop.
Only change the 1.2e+06 inside the “init” subpatch of recloopsavesampler.

Have a nice day

Aurélien Conil
Creative coding / D.I.Y / Pédagogie
http://aurelienconil.github.io <http://aurelienconil.github.io/>
http://assoundessens.fr <http://assoundessens.fr/>+33667485338

**Comment by ghost** [comment]
Hi,

So I need change on 2 places (pd init and right bottom) ONLY on /audio/recloopsavesampler.pd and /audio/recloopsave.pd ??? Thanks

**Comment by ghost** [comment]
Hi Aurelien,

do you know when is the new version of the looper will be finished?

Sur

**Comment by ghost** [comment]
Hi,

I've change the patches/audio/recloopsave.pd, patches/audio/recloopsavesampler.pd to 1.2e+07
on pd init and rightbottom but it doesn't work. Can you tell me what did I do wrong?
![Schermafbeelding 2020-05-12 om 11 19 38](https://user-images.githubusercontent.com/61553701/81666767-c0b41080-9442-11ea-9387-5dfde8820861.png)
![Schermafbeelding 2020-05-12 om 11 18 30](https://user-images.githubusercontent.com/61553701/81666777-c4479780-9442-11ea-85a7-03f0187a6cbd.png)

**Comment by ghost** [comment]
> Hi,
> 
> I've change the patches/audio/recloopsave.pd, patches/audio/recloopsavesampler.pd to 1.2e+07
> on pd init and rightbottom but it doesn't work. Can you tell me what did I do wrong?
> ![Schermafbeelding 2020-05-12 om 11 19 38](https://user-images.githubusercontent.com/61553701/81666767-c0b41080-9442-11ea-9387-5dfde8820861.png)
> ![Schermafbeelding 2020-05-12 om 11 18 30](https://user-images.githubusercontent.com/61553701/81666777-c4479780-9442-11ea-85a7-03f0187a6cbd.png)

Can you help me with this please?

**Comment by AurelienConil** [comment]
Ok. According to the version you have, you have to modify the right looper patch.
Open the main patch, where you are supposed to see 4 times the looper patch. 
Then you have to modify this looper patch( right clic -> open ) the exact way that you did ( pd init and right bottom corner ). This is the size of the array. If it doesn't, you will send me the files through email or we transfer, and i will do it for you

**Comment by ghost** [comment]
Thank you for your help. I did exactly as you said but it doesn't work. So please do it for me. This is the wetransfer link. https://wetransfer.com/downloads/f2458dd39197138c5fbc44d41bdd883420200514074933/3e0e96e8f960d5080b61fb399697199320200514075014/f45466

**Comment by AurelienConil** [comment]
ok, you send me only two files.
One is recloopsavesampler, and it is not the right one. you should forget about this file.
recloopsave is probably the one. You can verify, when looking at the "patch tab" of the main pd file, that there is 4 times recloopsave representing the 4 channels.
![Screenshot 2020-05-17 at 10 17 25](https://user-images.githubusercontent.com/16003353/82139471-3f84c100-9828-11ea-9842-066c4d4166ca.png)
In it, you can change the size of the array changing the number (in the circle ), then restart ( to recall the init ) and do a right click on the array itself ( the rectangle -> propreties ) to verify that your changes are effective.

Hope it will works

**Comment by ghost** [comment]
Hi Aurelien,
The patch is audio > recloopsaveundo.pd 
It works now! Thank you for your help!
Sur

**Comment by ghost** [comment]
Hi Aurelien,

I made the 'mute buttons' (check moon_loopstation.pd) and I would like to connect it to 'learn' (midiLearn.pd) How do you do that?
I am very new on PD and am learning it. 
I put all files on Google Drive https://drive.google.com/open?id=1CSpuR7y1F10naIZWwM_ukBqYayZ_pSO2
Sur
